export {
  AutomationEngine,
  AutomationError,
  type ActionAuthorization,
  type AutomationActionKind,
  type AutomationActionResult,
  type AutomationActionRisk,
  type AutomationEngineDependencies,
  type AutomationErrorCode,
  type AutomationPoint,
  type AutomationProviderDescriptor,
  type AutomationProviderPort,
  type AutomationRect,
  type AutomationSessionDescriptor,
  type ExecuteSemanticActionCommand,
  type OpenAutomationSessionCommand,
  type ProviderActionCommand,
  type ProviderActionResult,
  type ProviderLocator,
  type ResolvedActionTarget,
  type SemanticActionTarget,
} from "./automation-engine.js";
